Repository BrainPix/BrainPix-front, pull requests merged in 2025-02, with the labels that each got.

#53 feat: 마이페이지 - 포트폴리오 페이지 구현
  package-lock.json
  package.json
  src/App.tsx
  src/assets/icons/imageInput.svg
  src/assets/icons/search.svg
  src/components/common/carousel/Carousel.module.scss
  src/components/common/carousel/Carousel.tsx
  src/components/common/dropdown/Dropdown.tsx
  src/components/common/dropdown/dropdown.module.scss
  src/components/common/header/Header.tsx
  src/components/common/header/header.module.scss
  src/components/common/header/searchInput.module.scss
  src/components/common/levelCheckboxGroup/levelCheckboxGroup.module.scss
  src/components/my-page/Sidebar.tsx
  src/components/my-page/info/ExperiencePart.tsx
  src/components/my-page/info/IndividualInfoPart.tsx
  src/components/my-page/info/MyProfileCard.tsx
  src/components/my-page/info/PortfolioPart.tsx
  src/components/my-page/info/SkillPart.tsx
  src/components/my-page/info/SpecializationPart.tsx
  src/components/my-page/info/businessInfoPart.module.scss
  src/components/my-page/info/commonStyle.module.scss
  src/components/my-page/info/experiencePart.module.scss
  src/components/my-page/info/individualInfoPart.module.scss
  src/components/my-page/info/introducePart.module.scss
  src/components/my-page/info/myProfileCard.module.scss
  src/components/my-page/info/portfolioPart.module.scss
  src/components/my-page/info/skillPart.module.scss
  src/components/my-page/info/specializationPart.module.scss
  src/components/my-page/myPage/MyProfileCard.tsx
  src/components/my-page/myPage/PreviewList.tsx
  src/components/my-page/myPage/myProfileCard.module.scss
  src/components/my-page/myPage/previewList.module.scss
  src/components/my-page/portfolio/AddPortfolioModal.tsx
  src/components/my-page/portfolio/PortfolioDetailModal.tsx
  src/components/my-page/portfolio/QuillToolbar.tsx
  src/components/my-page/portfolio/addPortfolioModal.module.scss
  src/components/my-page/portfolio/portfolioDetailModal.module.scss
  src/components/my-page/portfolio/quillToolbar.module.scss
  src/components/my-page/sidebar.module.scss
  src/components/personal-profile/PortfolioCarousel.tsx
  src/components/personal-profile/PostsCarousel.tsx
  src/components/personal-profile/portfolioCarousel.module.scss
  src/components/postcard/PostCard.module.scss
  src/pages/layout/myPageLayout.module.scss
  src/pages/my-page/info/Info.tsx
  src/pages/my-page/info/info.module.scss
  src/pages/my-page/myPage/MyPage.tsx
  src/pages/my-page/myPage/myPage.module.scss
  src/pages/my-page/portfolio/ portfolio.module.scss
  src/pages/my-page/portfolio/Portfolio.tsx
  src/styles/_buttons.scss
  src/styles/_colors.scss
  src/styles/quillStyles.css
Labels: feature

#44 feat: 아이디어 마켓 메인페이지 구현
  package-lock.json
  src/App.tsx
  src/assets/icons/category.svg
  src/assets/icons/clickButton.svg
  src/components/recommend/RecommendedSection.tsx
  src/components/recommend/recommendedSection.module.scss
  src/pages/idea-market/IdeaMarket.tsx
  src/pages/idea-market/IdeaMarketMain.tsx
  src/pages/idea-market/IdeaMarketRegister.tsx
  src/pages/idea-market/ideaMarketMain.module.scss
  src/pages/idea-market/ideaMarketRegister.module.scss
Labels: feature

#57 feat: 마이페이지 - 메신저 페이지 구현
  src/App.tsx
  src/components/my-page/Sidebar.tsx
  src/components/my-page/message/WriteMessageModal.tsx
  src/components/my-page/message/writeMessageModal.module.scss
  src/components/my-page/portfolio/portfolioDetailModal.module.scss
  src/components/my-page/sidebar.module.scss
  src/constants/noMessageText.ts
  src/constants/temp.ts
  src/pages/my-page/message/Message.tsx
  src/pages/my-page/message/message.module.scss
  src/types/message.ts
Labels: feature

#56 feat: 마이페이지 하위 페이지(게시물 관리, 게시글) 구현
  src/App.tsx
  src/assets/icons/arrow-button.svg
  src/components/common/dropdown/dropdown.module.scss
  src/components/common/label/DeadlineLabel.tsx
  src/components/common/label/deadlineLabel.module.scss
  src/components/my-page/ApplyStatus.tsx
  src/components/my-page/CollaboPostHeader.tsx
  src/components/my-page/CurrentPeople.tsx
  src/components/my-page/IdeaMarketPostHeader.tsx
  src/components/my-page/PostFormAuthor.tsx
  src/components/my-page/PostFormContent.tsx
  src/components/my-page/PostFormIdeaTitle.tsx
  src/components/my-page/PostFormRecruitmentInfo.tsx
  src/components/my-page/PostFormRequestTitle.tsx
  src/components/my-page/PostHeader.tsx
  src/components/my-page/PurchaseStatus.tsx
  src/components/my-page/TabNavigation.tsx
  src/components/my-page/applyStatus.module.scss
  src/components/my-page/currentPeople.module.scss
  src/components/my-page/ideaMarketPostHeader.module.scss
  src/components/my-page/postFormAuthor.module.scss
  src/components/my-page/postFormIdeaTitle.module.scss
  src/components/my-page/postFormRecruitmentInfo.module.scss
  src/components/my-page/postFormRequestTitle.module.scss
  src/components/my-page/postHeader.module.scss
  src/components/my-page/purchaseStatus.module.scss
  src/components/my-page/tabNavigation.module.scss
  src/components/postcard/IdeaMarketPostCard.tsx
  src/components/postcard/PostCard.module.scss
  src/components/postcard/PostCard.tsx
  src/components/postcard/ideaMarketPostCard.module.scss
  src/components/postdetail/recruitmentInfo.module.scss
  src/pages/collaboration/postDetailWithLink.module.scss
  src/pages/my-page/myPagePosts/MyPagePosts.tsx
  src/pages/my-page/myPagePosts/myPagePosts.module.scss
  src/pages/my-page/postsCollaboration/CollaborationEdit.tsx
  src/pages/my-page/postsCollaboration/PostsCollaboration.tsx
  src/pages/my-page/postsIdeaMarket/IdeaMarketEdit.tsx
  src/pages/my-page/postsIdeaMarket/PostsIdeaMarket.tsx
  src/pages/my-page/postsIdeaMarket/postsIdeaMarket.module.scss
  src/pages/my-page/postsRequestAssign/PostsRequestAssign.tsx
  src/pages/my-page/postsRequestAssign/RequestAssignEdit.tsx
  src/pages/my-page/postsRequestAssign/RequestAssignRegister.tsx
  src/types/postData.ts
Labels: feature

#63 refactor: 로그인, 회원가입 디자인 수정
  package-lock.json
  package.json
  src/App.tsx
  src/apis/auth.ts
  src/assets/icons/individualMember.svg
  src/components/sign-up/Input.tsx
  src/components/sign-up/StepOne.tsx
  src/components/sign-up/StepTwo.tsx
  src/components/sign-up/commonSignup.module.scss
  src/components/sign-up/input.module.scss
  src/components/sign-up/stepOne.module.scss
  src/components/sign-up/stepTwo.module.scss
  src/constants/registers.ts
  src/pages/login/Login.tsx
  src/pages/login/login.module.scss
  src/pages/main/main.module.scss
  src/pages/main/main.tsx
  src/pages/sign-up/Signup.tsx
  src/pages/sign-up/corporate/CorporateMember.tsx
  src/pages/sign-up/corporate/corporateMember.module.scss
  src/pages/sign-up/individual/IndividualMember.tsx
  src/pages/sign-up/individual/individualMember.module.scss
  src/pages/sign-up/signup.module.scss
  src/styles/_buttons.scss
Labels: refactor

#64 style: 마이페이지 하위 페이지 일부 글로벌 변수 적용
  package-lock.json
  package.json
  src/assets/images/postCardImage.png
  src/components/common/dropdown/Dropdown.tsx
  src/components/my-page/applyStatus.module.scss
  src/components/my-page/currentPeople.module.scss
  src/components/my-page/ideaMarketPostHeader.module.scss
  src/components/my-page/info/IndividualInfoPart.tsx
  src/components/my-page/info/SpecializationPart.tsx
  src/components/my-page/portfolio/AddPortfolioModal.tsx
  src/components/my-page/postFormAuthor.module.scss
  src/components/my-page/postFormIdeaTitle.module.scss
  src/components/my-page/postFormRecruitmentInfo.module.scss
  src/components/my-page/postFormRequestTitle.module.scss
  src/components/my-page/postHeader.module.scss
  src/components/my-page/purchaseStatus.module.scss
  src/components/my-page/tabNavigation.module.scss
  src/components/postcard/PostCard.module.scss
  src/components/postcard/PostCard.tsx
  src/pages/idea-market/IdeaMarketMain.tsx
  src/pages/layout/myPageLayout.module.scss
  src/pages/my-page/myPagePosts/MyPagePosts.tsx
  src/pages/my-page/myPagePosts/myPagePosts.module.scss
  src/pages/my-page/postsIdeaMarket/postsIdeaMarket.module.scss
  src/pages/my-page/postsRequestAssign/RequestAssignRegister.tsx
  src/pages/my-page/postsRequestAssign/requestAssignRegister.module.scss
  src/pages/test/Test.tsx
  src/styles/_mixins.scss
  src/types/postData.ts
Labels: style

#69 feat: 로그인 API 연동
  src/apis/auth.ts
  src/apis/authAPI.ts
  src/components/common/button/ButtonGroup.tsx
  src/components/common/dropdown/Dropdown.tsx
  src/components/my-page/info/BusinessInfoPart.tsx
  src/components/my-page/info/IntroducePart.tsx
  src/components/my-page/info/SkillPart.tsx
  src/components/my-page/message/WriteMessageModal.tsx
  src/components/personal-profile/DescriptionTable.tsx
  src/components/postcard/IdeaMarketPostCard.tsx
  src/components/postcard/PostCard.tsx
  src/components/sign-up/StepTwo.tsx
  src/components/sign-up/stepTwo.module.scss
  src/constants/errorMessage.ts
  src/constants/registers.ts
  src/constants/temp.ts
  src/pages/login/Login.tsx
  src/pages/my-page/info/Info.tsx
  src/pages/my-page/message/Message.tsx
  src/pages/my-page/myPagePosts/MyPagePosts.tsx
  src/pages/personal-profile/PersonalProfile.tsx
  src/pages/sign-up/Signup.tsx
  src/types/auth.ts
  src/types/authType.ts
  src/types/messageType.ts
  src/types/postDataType.ts
  src/types/userDataType.ts
Labels: feature

#76 refactor: 로그인 API 수정
  src/App.tsx
  src/apis/authAPI.ts
  src/apis/profileAPI.ts
  src/assets/icons/checkInCicle.svg
  src/assets/icons/delete.svg
  src/assets/icons/error.svg
  src/assets/icons/eyeNonVisible.svg
  src/assets/icons/eyeVisible.svg
  src/assets/icons/infoInCircle.svg
  src/components/common/header/SearchInput.tsx
  src/components/common/toast/Toast.tsx
  src/components/common/toast/toast.module.scss
  src/components/sign-up/Input.tsx
  src/components/sign-up/StepOne.tsx
  src/components/sign-up/StepTwo.tsx
  src/components/sign-up/input.module.scss
  src/components/sign-up/stepTwo.module.scss
  src/constants/errorMessage.ts
  src/constants/registers.ts
  src/contexts/toastContext.tsx
  src/pages/login/Login.tsx
  src/pages/login/login.module.scss
  src/pages/main/main.tsx
  src/pages/sign-up/Signup.tsx
  src/pages/test/Test.tsx
  src/routes.tsx
  src/types/authType.ts
  src/types/profileType.ts
Labels: refactor

#79 refactor: 개인 프로필 조회 디자인에 맞춰 수정 완료
  src/components/common/carousel/Carousel.module.scss
  src/components/common/carousel/Carousel.tsx
  src/components/common/label/label.module.scss
  src/components/personal-profile/DescriptionTable.tsx
  src/components/personal-profile/PortfolioCarousel.tsx
  src/components/personal-profile/PostsCarousel.tsx
  src/components/personal-profile/ProfileCard.tsx
  src/components/personal-profile/descriptionTable.module.scss
  src/components/personal-profile/portfolioCarousel.module.scss
  src/components/personal-profile/postCarousel.module.scss
  src/components/personal-profile/profileCard.module.scss
  src/pages/personal-profile/PersonalProfile.tsx
  src/pages/personal-profile/personalProfile.module.scss
Labels: refactor

#82 refactor: 마이페이지 일부 css, 코드 수정
  src/components/common/label/DeadlineLabel.tsx
  src/components/common/label/deadlineLabel.module.scss
  src/components/my-page/ApplyStatus.tsx
  src/components/my-page/CurrentPeople.tsx
  src/components/my-page/IdeaMarketPostHeader.tsx
  src/components/my-page/PostFormIdeaTitle.tsx
  src/components/my-page/PostFormRecruitmentInfo.tsx
  src/components/my-page/PostFormRequestTitle.tsx
  src/components/my-page/PostHeader.tsx
  src/components/my-page/PurchaseStatus.tsx
  src/components/my-page/applyStatus.module.scss
  src/components/my-page/currentPeople.module.scss
  src/components/my-page/ideaMarketPostHeader.module.scss
  src/components/my-page/postFormAuthor.module.scss
  src/components/my-page/postFormIdeaTitle.module.scss
  src/components/my-page/postFormRecruitmentInfo.module.scss
  src/components/my-page/postFormRequestTitle.module.scss
  src/components/my-page/postHeader.module.scss
  src/components/my-page/purchaseStatus.module.scss
  src/pages/layout/myPageLayout.module.scss
  src/pages/my-page/postsCollaboration/PostsCollaboration.tsx
  src/pages/my-page/postsIdeaMarket/IdeaMarketEdit.tsx
  src/pages/my-page/postsIdeaMarket/PostsIdeaMarket.tsx
  src/pages/my-page/postsIdeaMarket/postsIdeaMarket.module.scss
  src/pages/my-page/postsRequestAssign/PostsRequestAssign.tsx
  src/pages/my-page/postsRequestAssign/RequestAssignRegister.tsx
  src/routes.tsx
Labels: refactor

#75 feat: 마이페이지 지원 현황 페이지 구현
  eslint.config.js
  package-lock.json
  package.json
  src/assets/icons/arrowButton.svg
  src/assets/icons/messageArrowButton.svg
  src/components/common/label/Label.tsx
  src/components/common/label/label.module.scss
  src/components/my-page/PostFormAuthor.tsx
  src/components/my-page/PostHeader.tsx
  src/components/my-page/Sidebar.tsx
  src/components/my-page/apply/ApplyDetailsInfo.tsx
  src/components/my-page/apply/ApplyTable.tsx
  src/components/my-page/apply/CardHeader.tsx
  src/components/my-page/apply/PayInfo.tsx
  src/components/my-page/apply/PostAuthorInfo.tsx
  src/components/my-page/apply/PurchaseDetailsInfo.tsx
  src/components/my-page/apply/applyTable.module.scss
  src/components/my-page/apply/cardHeader.module.scss
  src/components/my-page/apply/itemDetailsInfo.module.scss
  src/components/my-page/apply/payInfo.module.scss
  src/components/my-page/apply/postAuthorInfo.module.scss
  src/components/my-page/sidebar.module.scss
  src/components/my-page/tabNavigation.module.scss
  src/pages/my-page/apply/ApplyCollaboration.tsx
  src/pages/my-page/apply/ApplyRequest.tsx
  src/pages/my-page/apply/PurchaseList.tsx
  src/pages/my-page/apply/applyCollaboration.module.scss
  src/pages/my-page/apply/applyRequest.module.scss
  src/pages/my-page/apply/purchaseList.module.scss
  src/pages/my-page/myPagePosts/MyPagePosts.tsx
  src/pages/my-page/myPagePosts/myPagePosts.module.scss
  src/pages/my-page/postsCollaboration/CollaborationEdit.tsx
  src/pages/my-page/postsIdeaMarket/IdeaMarketEdit.tsx
  src/pages/my-page/postsRequestAssign/RequestAssignEdit.tsx
  src/routes.tsx
  src/styles/_colors.scss
  src/utils/isValidLabelType.ts
Labels: feature

#88 feat: 포트폴리오 관리 API 연동
  package-lock.json
  package.json
  src/App.tsx
  src/apis/alarmAPI.ts
  src/apis/authAPI.ts
  src/apis/commonAPI.ts
  src/apis/mypageAPI.ts
  src/apis/portfolio.ts
  src/apis/profileAPI.ts
  src/components/common/dropdown/Dropdown.tsx
  src/components/common/header/Header.tsx
  src/components/common/header/header.module.scss
  src/components/common/toast/toast.module.scss
  src/components/my-page/info/BusinessInfoPart.tsx
  src/components/my-page/info/ExperiencePart.tsx
  src/components/my-page/info/IndividualInfoPart.tsx
  src/components/my-page/info/IntroducePart.tsx
  src/components/my-page/info/MyProfileCard.tsx
  src/components/my-page/info/PortfolioPart.tsx
  src/components/my-page/info/SkillPart.tsx
  src/components/my-page/info/SpecializationPart.tsx
  src/components/my-page/info/individualInfoPart.module.scss
  src/components/my-page/info/portfolioPart.module.scss
  src/components/my-page/info/skillPart.module.scss
  src/components/my-page/info/specializationPart.module.scss
  src/components/my-page/myPage/MyProfileCard.tsx
  src/components/my-page/portfolio/AddPortfolioModal.tsx
  src/components/my-page/portfolio/DeleteCheckModal.tsx
  src/components/my-page/portfolio/PortfolioDetailModal.tsx
  src/components/my-page/portfolio/addPortfolioModal.module.scss
  src/components/my-page/portfolio/deleteCheckModal.module.scss
  src/components/my-page/portfolio/portfolioDetailModal.module.scss
  src/components/postdetail/AuthorInfo.tsx
  src/components/registeredPage/PostTitleApply.tsx
  src/components/registeredPage/PostTitlePay.tsx
  src/components/sign-up/CompleteSignup.tsx
  src/components/sign-up/StepOne.tsx
  src/components/sign-up/StepTwo.tsx
  src/components/sign-up/completeSignup.module.scss
  src/constants/categoryMapper.ts
  src/constants/initValues.ts
  src/hooks/useIntersectionObserverAPI.ts
  src/pages/login/Login.tsx
  src/pages/main/main.tsx
  src/pages/my-page/info/Info.tsx
  src/pages/my-page/info/info.module.scss
  src/pages/my-page/myPage/MyPage.tsx
  src/pages/my-page/portfolio/Portfolio.tsx
  src/pages/my-page/portfolio/portfolio.module.scss
  src/pages/request-assign/RequestRegisteredPage.tsx
  src/pages/sign-up/Signup.tsx
  src/routes.tsx
  src/styles/_colors.scss
  src/types/myPageType.ts
  src/types/profileType.ts
  src/utils/categoryMapping.ts
  src/utils/formatSpecialization.ts
  src/utils/formatToLabelText.ts
  src/utils/imageErrorHandler.ts
Labels: feature

#89 feat: 마이페이지 API 연동
  src/apis/authAPI.ts
  src/apis/mypageAPI.ts
  src/components/common/carousel/Carousel.module.scss
  src/components/common/carousel/Carousel.tsx
  src/components/my-page/info/BusinessInfoPart.tsx
  src/components/my-page/info/ExperiencePart.tsx
  src/components/my-page/info/IndividualInfoPart.tsx
  src/components/my-page/info/IntroducePart.tsx
  src/components/my-page/info/MyProfileCard.tsx
  src/components/my-page/info/PortfolioPart.tsx
  src/components/my-page/info/SkillPart.tsx
  src/components/my-page/info/SpecializationPart.tsx
  src/components/my-page/info/businessInfoPart.module.scss
  src/components/my-page/info/commonStyle.module.scss
  src/components/my-page/info/experiencePart.module.scss
  src/components/my-page/info/individualInfoPart.module.scss
  src/components/my-page/info/myProfileCard.module.scss
  src/components/my-page/info/portfolioPart.module.scss
  src/components/my-page/info/skillPart.module.scss
  src/components/my-page/info/specializationPart.module.scss
  src/components/my-page/myPage/MyProfileCard.tsx
  src/constants/categoryMapper.ts
  src/pages/login/Login.tsx
  src/pages/main/main.tsx
  src/pages/my-page/info/Info.tsx
  src/pages/my-page/myPage/MyPage.tsx
  src/pages/sign-up/Signup.tsx
  src/routes.tsx
  src/types/myPageType.ts
  src/types/profileType.ts
  src/utils/imageLoader.ts
Labels: feature

#93 feat: 마이페이지 게시물 관리, 지원 현황 API 연동 완료
  src/apis/postManagementAPI.ts
  src/apis/supportsAPI.ts
  src/assets/icons/arrow-button.svg
  src/components/my-page/ApplyStatus.tsx
  src/components/my-page/CurrentPeople.tsx
  src/components/my-page/IdeaMarketPostHeader.tsx
  src/components/my-page/PostHeader.tsx
  src/components/my-page/PurchaseStatus.tsx
  src/components/my-page/apply/ApplyDetailsInfo.tsx
  src/components/my-page/apply/CardHeader.tsx
  src/components/my-page/apply/PurchaseDetailsInfo.tsx
  src/components/my-page/ideaMarketPostHeader.module.scss
  src/components/my-page/postHeader.module.scss
  src/components/postcard/IdeaMarketPostCard.tsx
  src/components/postcard/PostCard.module.scss
  src/components/postcard/PostCard.tsx
  src/components/postcard/ideaMarketPostCard.module.scss
  src/components/preview/PreviewThumbnail.tsx
  src/pages/my-page/apply/ApplyCollaboration.tsx
  src/pages/my-page/apply/ApplyRequest.tsx
  src/pages/my-page/apply/PurchaseList.tsx
  src/pages/my-page/myPagePosts/MyPagePosts.tsx
  src/pages/my-page/postsCollaboration/PostsCollaboration.tsx
  src/pages/my-page/postsIdeaMarket/PostsIdeaMarket.tsx
  src/pages/my-page/postsRequestAssign/PostsRequestAssign.tsx
  src/types/postDataType.ts
  src/types/supportsType.ts
  src/utils/dateUtils.ts
Labels: feature

#95 feat: 개인 프로필 API 연동
  src/apis/portfolio.ts
  src/apis/profileAPI.ts
  src/components/common/carousel/Carousel.tsx
  src/components/common/label/label.module.scss
  src/components/my-page/info/MyProfileCard.tsx
  src/components/my-page/info/PortfolioPart.tsx
  src/components/my-page/info/myProfileCard.module.scss
  src/components/my-page/myPage/previewList.module.scss
  src/components/my-page/portfolio/AddPortfolioModal.tsx
  src/components/my-page/portfolio/PortfolioDetailModal.tsx
  src/components/personal-profile/DescriptionTable.tsx
  src/components/personal-profile/PortfolioCarousel.tsx
  src/components/personal-profile/PortfolioPopup.tsx
  src/components/personal-profile/PostsCarousel.tsx
  src/components/personal-profile/ProfileCard.tsx
  src/components/personal-profile/descriptionTable.module.scss
  src/components/personal-profile/portfolioCarousel.module.scss
  src/components/personal-profile/portfolioPopup.module.scss
  src/components/personal-profile/postCarousel.module.scss
  src/components/personal-profile/profileCard.module.scss
  src/constants/initValues.ts
  src/pages/login/Login.tsx
  src/pages/my-page/myPage/myPage.module.scss
  src/pages/my-page/portfolio/Portfolio.tsx
  src/pages/personal-profile/PersonalProfile.tsx
  src/routes.tsx
  src/styles/_fonts.scss
  src/types/myPageType.ts
  src/types/postDataType.ts
  src/types/profileType.ts
  src/utils/calculateDday.ts
Labels: feature

#101 refactor: 헤더 수정
  src/components/common/header/Header.tsx
  src/components/common/header/header.module.scss
  src/components/common/header/searchInput.module.scss
Labels: refactor

#111 refactor: 전반적인 오류 수정
  src/apis/postManagementAPI.ts
  src/apis/savePostsAPI.ts
  src/components/my-page/info/IndividualInfoPart.tsx
  src/components/my-page/info/MyProfileCard.tsx
  src/components/my-page/info/individualInfoPart.module.scss
  src/components/personal-profile/PortfolioCarousel.tsx
  src/components/personal-profile/PostsCarousel.tsx
  src/components/personal-profile/descriptionTable.module.scss
  src/components/personal-profile/portfolioCarousel.module.scss
  src/components/personal-profile/postCarousel.module.scss
  src/components/sign-up/StepTwo.tsx
  src/components/sign-up/input.module.scss
  src/components/sign-up/stepTwo.module.scss
  src/constants/registers.ts
  src/pages/errorPage/ErrorPage.tsx
  src/pages/errorPage/errorPage.module.scss
  src/pages/login/Login.tsx
  src/pages/login/login.module.scss
  src/pages/sign-up/Signup.tsx
  src/pages/sign-up/signup.module.scss
  src/routes.tsx
Labels: fix, refactor

#112 refactor: 전체적 수정
  src/apis/kakaoAPI.ts
  src/components/payment/PaymentApproval.tsx
  src/components/payment/PaymentSummary.tsx
  src/components/payment/paymentSummary.module.scss
  src/components/postdetail/AuthorInfo.tsx
  src/components/postdetail/PostHeader.tsx
  src/components/postdetail/profileHeader.module.scss
  src/components/registeredPage/PostTitleApply.tsx
  src/components/registeredPage/PostTitlePay.tsx
  src/components/registeredPage/postTitle.module.scss
  src/components/registeredPage/profileHeader.module.scss
  src/pages/collaboration/PostDetailWithLink.tsx
  src/pages/idea-market/IdeaRegisteredPage.tsx
  src/pages/idea-market/PaymentProcessing.tsx
  src/pages/my-page/postsIdeaMarket/IdeaMarketRegistered.tsx
  src/pages/my-page/postsRequestAssign/RequestAssignRegistered.tsx
  src/pages/request-assign/RequestRegisteredPage.tsx
  src/types/detailPageType.ts
Labels: refactor, feature

#114 fix: img 태그 -> Image 태그로 수정
  src/apis/postManagementAPI.ts
  src/components/common/loading/LoadingPage.tsx
  src/components/common/loading/loadingPage.module.scss
  src/components/common/modal/CollaborationSupportModal.tsx
  src/components/common/modal/RequestSupportModal.tsx
  src/components/common/modal/supportModal.module.scss
  src/components/error/LoadingSpinner.tsx
  src/components/error/loadingSpinner.module.scss
  src/components/my-page/PostHeader.tsx
  src/components/my-page/ProfileHeaderAuthor.tsx
  src/components/my-page/edit/ButtonGroup.tsx
  src/components/my-page/edit/ImageUploader.tsx
  src/components/my-page/portfolio/PortfolioDetailModal.tsx
  src/components/personal-profile/PortfolioCarousel.tsx
  src/components/personal-profile/PostsCarousel.tsx
  src/components/personal-profile/portfolioCarousel.module.scss
  src/components/postdetail/TeamBuildingButton.tsx
  src/components/preview/PreviewThumbnail.tsx
  src/components/registeredPage/PostTitleApply.tsx
  src/pages/collaboration/CollaborationMain.tsx
  src/pages/idea-market/IdeaMarketMain.tsx
  src/pages/idea-market/IdeaMarketMarketPlace.tsx
  src/pages/idea-market/IdeaMarketPayment.tsx
  src/pages/idea-market/IdeaRegisteredPage.tsx
  src/pages/idea-market/PaymentFail.tsx
  src/pages/idea-market/PaymentSuccess.tsx
  src/pages/loading/LoadingPage.tsx
  src/pages/loading/loadingPage.module.scss
  src/pages/login/Login.tsx
  src/pages/my-page/apply/ApplyCollaboration.tsx
  src/pages/my-page/apply/ApplyRequest.tsx
  src/pages/my-page/apply/PurchaseList.tsx
  src/pages/my-page/info/Info.tsx
  src/pages/my-page/message/Message.tsx
  src/pages/my-page/myPage/MyPage.tsx
  src/pages/my-page/myPage/RecentNews.tsx
  src/pages/my-page/myPagePosts/MyPagePosts.tsx
  src/pages/my-page/postsCollaboration/PostsCollaboration.tsx
  src/pages/my-page/postsIdeaMarket/IdeaMarketEdit.tsx
  src/pages/my-page/postsIdeaMarket/IdeaMarketRegistered.tsx
  src/pages/my-page/postsIdeaMarket/PostsIdeaMarket.tsx
  src/pages/my-page/postsIdeaMarket/postsIdeaMarket.module.scss
  src/pages/my-page/postsRequestAssign/PostsRequestAssign.tsx
  src/pages/my-page/postsRequestAssign/RequestAssignRegistered.tsx
  src/pages/my-page/saved-posts/SavedPosts.tsx
  src/pages/personal-profile/PersonalProfile.tsx
  src/pages/request-assign/RequestAssignMain.tsx
  src/pages/request-assign/RequestAssignTechZone.tsx
  src/pages/request-assign/RequestRegisteredPage.tsx
Labels: fix

#117 feat: 무한스크롤 구현
  src/apis/collaborationAPI.ts
  src/apis/mainPageAPI.ts
  src/apis/requestAssignMainPageAPI.ts
  src/components/error/loadingSpinner.module.scss
  src/components/preview/PreviewThumbnail.tsx
  src/components/preview/previewThumbnail.module.scss
  src/pages/collaboration/CollaborationMain.tsx
  src/pages/collaboration/CollaborationRegister.tsx
  src/pages/collaboration/collaborationMain.module.scss
  src/pages/collaboration/collaborationRegister.module.scss
  src/pages/idea-market/IdeaMarketMain.tsx
  src/pages/idea-market/IdeaMarketMarketPlace.tsx
  src/pages/idea-market/IdeaMarketRegister.tsx
  src/pages/idea-market/ideaMarketMain.module.scss
  src/pages/request-assign/RequestAssignMain.tsx
  src/pages/request-assign/RequestAssignRegister.tsx
  src/pages/request-assign/RequestAssignTechZone.tsx
  src/pages/request-assign/requestAssignMain.module.scss
  src/pages/request-assign/requestAssignRegister.module.scss
  src/pages/request-assign/requestAssignRegisterComplete.module.scss
  src/pages/request-assign/requestAssignTechZone.module.scss
  src/types/collaborationType.ts
  src/types/mainType.ts
  src/types/registerType.ts
Labels: feature

#118 refactor: 페이지 상세 title 깨지는 부분 수정
  src/components/postdetail/TaskDescription.tsx
  src/components/postdetail/postHeader.module.scss
  src/components/registeredPage/IdeaDescription.tsx
  src/components/registeredPage/postTitle.module.scss
Labels: refactor

#116 feat: 비회원이 기업 공개 페이지 접근 시 로직 및 페이지 구현
  src/apis/detailPageAPI.ts
  src/components/common/levelCheckboxGroup/LevelCheckboxGroup.tsx
  src/components/my-page/info/IntroducePart.tsx
  src/components/my-page/info/individualInfoPart.module.scss
  src/components/my-page/message/WriteMessageModal.tsx
  src/components/my-page/message/writeMessageModal.module.scss
  src/components/my-page/myPage/previewList.module.scss
  src/components/personal-profile/PostsCarousel.tsx
  src/pages/idea-market/IdeaRegisteredPage.tsx
  src/pages/join/Join.tsx
  src/pages/join/join.module.scss
  src/pages/my-page/myPage/RecentNews.tsx
  src/pages/request-assign/RequestRegisteredPage.tsx
  src/types/postDataType.ts
Labels: feature

#120 refactor: 카카오페이 제외 다른 버튼 text 삭제
  src/components/common/label/label.module.scss
  src/components/payment/PaymentSummary.tsx
  src/components/postdetail/authorInfo.module.scss
  src/components/postdetail/taskDescription.module.scss
  src/components/registeredPage/postTitle.module.scss
Labels: refactor

#119 refactor: 전반적인 리팩토링 작업 및 오류 수정
  src/apis/supportsAPI.ts
  src/components/my-page/ApplyStatus.tsx
  src/components/my-page/CurrentPeople.tsx
  src/components/my-page/IdeaMarketPostHeader.tsx
  src/components/my-page/PostHeader.tsx
  src/components/my-page/apply/ApplyDetailsInfo.tsx
  src/components/my-page/apply/ApplyTable.tsx
  src/components/my-page/apply/PostAuthorInfo.tsx
  src/components/my-page/apply/PurchaseDetailsInfo.tsx
  src/constants/categoryMapper.ts
  src/pages/my-page/apply/ApplyCollaboration.tsx
  src/pages/my-page/apply/ApplyRequest.tsx
  src/pages/my-page/apply/PurchaseList.tsx
  src/pages/my-page/postsCollaboration/PostsCollaboration.tsx
  src/pages/my-page/postsIdeaMarket/PostsIdeaMarket.tsx
  src/pages/my-page/postsRequestAssign/PostsRequestAssign.tsx
  src/types/postDataType.ts
  src/utils/categoryMapping.ts
Labels: refactor
