Repository BrainPix/BrainPix-front, pull requests merged in 2025-01, with the labels that each got.

#2 Setting/project setup
  .github/workflows/github-actions.yml
  .gitignore
  .prettierrc
  .stylelintrc.json
  README.md
  eslint.config.js
  index.html
  package-lock.json
  package.json
  public/vite.svg
  src/App.tsx
  src/global.d.ts
  src/index.css
  src/main.tsx
  src/pages/test/Test.tsx
  src/pages/test/test.module.scss
  src/styles/_mixins.scss
  src/styles/global.scss
  src/vite-env.d.ts
  tsconfig.app.json
  tsconfig.json
  tsconfig.node.json
  vite.config.ts
Labels: setting

#7 feat: navbar 컴포넌트 구현
  .github/ISSUE_TEMPLATE/issue-✨feature.md
  .github/ISSUE_TEMPLATE/♻️refactor.md
  .github/ISSUE_TEMPLATE/🎨style.md
  .github/ISSUE_TEMPLATE/🐛fix.md
  .github/ISSUE_TEMPLATE/📝docs.md
  .github/ISSUE_TEMPLATE/🔧setting.md
  .github/ISSUE_TEMPLATE/🧹chore.md
  .github/workflows/github-actions.yml
  README.md
  eslint.config.js
  index.html
  package-lock.json
  package.json
  src/App.tsx
  src/assets/icons/clock.svg
  src/assets/icons/delete.svg
  src/assets/icons/search.svg
  src/components/header/Header.tsx
  src/components/header/SearchInput.tsx
  src/components/header/header.module.scss
  src/components/header/searchInput.module.scss
  src/hooks/useOutsideClick.ts
  src/index.css
  src/main.tsx
  src/pages/collaboration/Collaboration.tsx
  src/pages/idea-market/IdeaMarket.tsx
  src/pages/layout/Layout.tsx
  src/pages/request-assign/RequestAssign.tsx
  src/styles/global.scss
  src/utils/debounce.ts
  src/vite-env.d.ts
  vite.config.ts
Labels: feature

#9 feat: 취소/등록 버튼 컴포넌트 구현
  src/components/button/ButtonGroup.tsx
  src/components/button/buttonGroup.module.scss
  src/pages/test/Test.tsx
  src/pages/test/test.module.scss
Labels: feature

#13 feat: 아이디어 마켓 - 결제페이지 ui 구현
  src/App.tsx
  src/assets/icons/Ellipse_blue.svg
  src/assets/icons/Ellipse_gray.svg
  src/assets/icons/Ellipse_white.svg
  src/assets/icons/check-light-blue.svg
  src/assets/icons/check-light-gray.svg
  src/assets/icons/check-light.svg
  src/components/button/PaymentButton.module.scss
  src/components/button/PaymentButton.tsx
  src/components/info/SellerInfo.module.scss
  src/components/info/SellerInfo.tsx
  src/components/payment/PaymentMethods.module.scss
  src/components/payment/PaymentMethods.tsx
  src/components/payment/PaymentSummary.module.scss
  src/components/payment/PaymentSummary.tsx
  src/components/payment/PaymentTitle.module.scss
  src/components/payment/PaymentTitle.tsx
  src/pages/idea-market/IdeaMarketPayment/IdeaMarketPayment.module.scss
  src/pages/idea-market/IdeaMarketPayment/IdeaMarketPayment.tsx
  vite.config.ts
Labels: feature

#12 feat: 회원가입 페이지 구현
  src/App.tsx
  src/assets/icons/corporateMember.svg
  src/assets/icons/individualMember.svg
  src/components/header/header.module.scss
  src/pages/sign-up/CompleteSignup.tsx
  src/pages/sign-up/CorporateMember.tsx
  src/pages/sign-up/IndividualMember.tsx
  src/pages/sign-up/Input.tsx
  src/pages/sign-up/Signup.tsx
  src/pages/sign-up/commonSignup.module.scss
  src/pages/sign-up/completeSignup.module.scss
  src/pages/sign-up/corporateMember.module.scss
  src/pages/sign-up/individualMember.module.scss
  src/pages/sign-up/input.module.scss
  src/pages/sign-up/signUp.module.scss
  src/styles/global.scss
Labels: feature

#16 fix: svgr 플러그인 수정
  vite.config.ts
Labels: fix

#17 feat : 카테고리 드롭다운 버튼 구현
  package-lock.json
  package.json
  src/components/dropdown/Dropdown.tsx
  src/components/dropdown/dropdown.module.scss
  src/pages/test/Test.tsx
  src/styles/_mixins.scss
Labels: feature

#26 chore: 배포 및 배포 자동화 적용
  .github/workflows/github-actions.yml
  .github/workflows/sync-to-fork.yml
  vercel.json
Labels: chore

#34 style: global scss 추가
  src/styles/_buttons.scss
  src/styles/_components.scss
  src/styles/_layout.scss
  src/styles/_reset.scss
  src/styles/_variables.scss
  src/styles/main.scss
Labels: style

#30 feat: 개별 협업 게시글
  src/App.tsx
  src/assets/icons/arrow-up-2-thin.svg
  src/assets/icons/bookmark-fill.svg
  src/assets/icons/dot.svg
  src/assets/icons/empty-circle.svg
  src/assets/icons/shortcut-arrow.svg
  src/components/common/label/CorporateLabel.tsx
  src/components/common/label/CorporatePublicLabel.tsx
  src/components/common/label/PersonalLabel.tsx
  src/components/common/label/SelfOfferLabel.tsx
  src/components/common/label/corporateLabel.module.scss
  src/components/common/label/corporatePublicLabel.module.scss
  src/components/common/label/personalLabel.module.scss
  src/components/common/label/selfOfferLabel.module.scss
  src/components/payment/PaymentButton.tsx
  src/components/payment/PaymentMethods.tsx
  src/components/payment/PaymentSummary.tsx
  src/components/payment/PaymentTitle.tsx
  src/components/payment/SellerInfo.tsx
  src/components/payment/paymentButton.module.scss
  src/components/payment/paymentMethods.module.scss
  src/components/payment/paymentSummary.module.scss
  src/components/payment/paymentTitle.module.scss
  src/components/payment/sellerInfo.module.scss
  src/components/postdetail/AuthorInfo.tsx
  src/components/postdetail/PostHeader.tsx
  src/components/postdetail/ProfileHeader.tsx
  src/components/postdetail/QnASection.tsx
  src/components/postdetail/RecruitmentInfo.tsx
  src/components/postdetail/RecruitmentStatus.tsx
  src/components/postdetail/TaskDescription.tsx
  src/components/postdetail/TeamBuildingButton.tsx
  src/components/postdetail/WebLinkBox.tsx
  src/components/postdetail/authorInfo.module.scss
  src/components/postdetail/postHeader.module.scss
  src/components/postdetail/profileHeader.module.scss
  src/components/postdetail/qnaSection.module.scss
  src/components/postdetail/recruitmentInfo.module.scss
  src/components/postdetail/recruitmentStatus.module.scss
  src/components/postdetail/taskDescription.module.scss
  src/components/postdetail/teamBuildingButton.module.scss
  src/components/postdetail/webLinkBox.module.scss
  src/pages/collaboration/PostDetailWithLink.tsx
  src/pages/collaboration/PostDetailWithoutLink.tsx
  src/pages/collaboration/postDetailWithLink.module.scss
  src/pages/collaboration/postDetailWithoutLink.module.scss
  src/pages/idea-market/IdeaMarketPayment.tsx
  src/pages/idea-market/IdeaMarketPayment/IdeaMarketPayment.tsx
  src/pages/idea-market/ideaMarketPayment.module.scss
  src/pages/test/Test.tsx
Labels: refactor, feature

#35 refactor: 게시글 사진 부분 수정
  src/components/preview/PreviewThumbnail.tsx
  src/components/preview/previewThumbnail.module.scss
Labels: refactor

#28 feat: 마이페이지 - 게시물 관리 페이지 구현
  src/App.tsx
  src/components/dropdown/dropdown.module.scss
  src/components/postcard/PostCard.module.scss
  src/components/postcard/PostCard.tsx
  src/components/sidebar/MyPageSidebar.tsx
  src/components/sidebar/myPageSidebarTemp.module.scss
  src/components/tab-navigation/TabNavigation.tsx
  src/components/tab-navigation/tabNavigation.module.scss
  src/pages/mypage/MyPagePosts/MyPagePosts.tsx
  src/pages/mypage/MyPagePosts/myPagePosts.module.scss
  src/pages/mypage/PostsIdeaMarket/PostsIdeaMarket.tsx
  src/pages/mypage/PostsIdeaMarket/postsIdeaMarket.module.scss
Labels: feature

#42 feat: 마이페이지-기본페이지 구현
  src/App.tsx
  src/components/common/header/header.module.scss
  src/components/my/MyProfileCard.tsx
  src/components/my/PreviewList.tsx
  src/components/my/Sidebar.tsx
  src/components/my/myProfileCard.module.scss
  src/components/my/previewList.module.scss
  src/components/my/sidebar.module.scss
  src/pages/collaboration/PostDetailWithLink.tsx
  src/pages/collaboration/PostDetailWithoutLink.tsx
  src/pages/idea-market/IdeaMarket.tsx
  src/pages/idea-market/IdeaMarketPayment.tsx
  src/pages/layout/MyPageLayout.tsx
  src/pages/layout/myPageLayout.module.scss
  src/pages/my-page/myPage/MyPage.tsx
  src/pages/my-page/myPage/myPage.module.scss
  src/pages/my-page/myPagePosts/MyPagePosts.tsx
  src/pages/my-page/myPagePosts/myPagePosts.module.scss
  src/pages/my-page/postsIdeaMarket/PostsIdeaMarket.tsx
  src/pages/my-page/postsIdeaMarket/postsIdeaMarket.module.scss
  src/pages/personal-profile/PersonalProfile.tsx
  src/pages/personal-profile/personalProfile.module.scss
Labels: feature

#48 feat: 마이페이지 최근 소식 구현
  src/App.tsx
  src/assets/icons/trash.svg
  src/assets/icons/undo.svg
  src/components/common/dropdown/Dropdown.tsx
  src/components/common/dropdown/dropdown.module.scss
  src/components/my-page/MyProfileCard.tsx
  src/components/my-page/PreviewList.tsx
  src/components/my-page/Sidebar.tsx
  src/components/my-page/myProfileCard.module.scss
  src/components/my-page/previewList.module.scss
  src/components/my-page/sidebar.module.scss
  src/components/my/sidebar.module.scss
  src/components/sidebar/MyPageSidebar.tsx
  src/components/sidebar/myPageSidebarTemp.module.scss
  src/components/tab-navigation/TabNavigation.tsx
  src/components/tab-navigation/tabNavigation.module.scss
  src/pages/layout/MyPageLayout.tsx
  src/pages/my-page/myPage/MyPage.tsx
  src/pages/my-page/myPage/RecentNews.tsx
  src/pages/my-page/myPage/myPage.module.scss
  src/pages/my-page/myPage/recentNews.module.scss
  src/pages/my-page/myPagePosts/MyPagePosts.tsx
  src/pages/test/Test.tsx
  src/styles/_buttons.scss
Labels: feature

#45 feat: 등록된 페이지 ui 구현
  src/App.tsx
  src/assets/icons/arrowUp2Thin.svg
  src/assets/icons/bookmarkFill.svg
  src/assets/icons/checkLight.svg
  src/assets/icons/checkLightBlue.svg
  src/assets/icons/checkLightGray.svg
  src/assets/icons/ellipseBlue.svg
  src/assets/icons/ellipseGray.svg
  src/assets/icons/ellipseWhite.svg
  src/assets/icons/emptyCircle.svg
  src/assets/icons/shortcutArrow.svg
  src/assets/icons/upDownButton.svg
  src/components/common/label/CorporateLabel.tsx
  src/components/common/label/CorporatePublicLabel.tsx
  src/components/common/label/Label.tsx
  src/components/common/label/PersonalLabel.tsx
  src/components/common/label/SelfOfferLabel.tsx
  src/components/common/label/corporateLabel.module.scss
  src/components/common/label/corporatePublicLabel.module.scss
  src/components/common/label/label.module.scss
  src/components/common/label/personalLabel.module.scss
  src/components/common/label/selfOfferLabel.module.scss
  src/components/modal/CollaborationSupportModal.tsx
  src/components/modal/RequestSupportModal.tsx
  src/components/modal/supportModal.module.scss
  src/components/payment/PaymentSummary.tsx
  src/components/payment/PaymentTitle.tsx
  src/components/payment/paymentTitle.module.scss
  src/components/postdetail/AuthorInfo.tsx
  src/components/postdetail/PostHeader.tsx
  src/components/postdetail/ProfileHeader.tsx
  src/components/postdetail/TeamBuildingButton.tsx
  src/components/postdetail/WebLinkBox.tsx
  src/components/postdetail/postHeader.module.scss
  src/components/postdetail/teamBuildingButton.module.scss
  src/components/registeredPage/AssignmentDescription.tsx
  src/components/registeredPage/IdeaDescription.tsx
  src/components/registeredPage/PostTitleApply.tsx
  src/components/registeredPage/PostTitlePay.tsx
  src/components/registeredPage/assignmentDescription.module.scss
  src/components/registeredPage/ideaDescription.module.scss
  src/components/registeredPage/postTitle.module.scss
  src/pages/idea-market/IdeaRegisteredPage.tsx
  src/pages/idea-market/ideaRegisteredPage.module.scss
  src/pages/request-assign/RequestRegisteredPage.tsx
  src/pages/request-assign/requestRegisteredPage.module.scss
  src/pages/test/Test.tsx
Labels: feature

#51 feat: 마이페이지 - 내 정보 구현
  src/App.tsx
  src/components/common/Carousel/Carousel.tsx
  src/components/common/dropdown/Dropdown.tsx
  src/components/common/dropdown/dropdown.module.scss
  src/components/common/levelCheckboxGroup/LevelCheckboxGroup.tsx
  src/components/common/levelCheckboxGroup/levelCheckboxGroup.module.scss
  src/components/my-page/Sidebar.tsx
  src/components/my-page/info/BusinessInfoPart.tsx
  src/components/my-page/info/ExperiencePart.tsx
  src/components/my-page/info/IndividualInfoPart.tsx
  src/components/my-page/info/IntroducePart.tsx
  src/components/my-page/info/MyProfileCard.tsx
  src/components/my-page/info/PortfolioPart.tsx
  src/components/my-page/info/SkillPart.tsx
  src/components/my-page/info/SpecializationPart.tsx
  src/components/my-page/info/businessInfoPart.module.scss
  src/components/my-page/info/commonStyle.module.scss
  src/components/my-page/info/experiencePart.module.scss
  src/components/my-page/info/individualInfoPart.module.scss
  src/components/my-page/info/introducePart.module.scss
  src/components/my-page/info/myProfileCard.module.scss
  src/components/my-page/info/portfolioPart.module.scss
  src/components/my-page/info/skillPart.module.scss
  src/components/my-page/info/specializationPart.module.scss
  src/components/my-page/myPage/MyProfileCard.tsx
  src/components/my-page/myPage/PreviewList.tsx
  src/components/my-page/myPage/myProfileCard.module.scss
  src/components/my-page/myPage/previewList.module.scss
  src/components/personal-profile/PortfolioCarousel.tsx
  src/components/personal-profile/portfolioCarousel.module.scss
  src/components/personal-profile/portfolioPopup.module.scss
  src/pages/my-page/info/Info.tsx
  src/pages/my-page/info/info.module.scss
  src/pages/my-page/myPage/MyPage.tsx
  src/pages/my-page/myPage/RecentNews.tsx
  src/pages/personal-profile/PersonalProfile.tsx
  src/pages/personal-profile/personalProfile.module.scss
Labels: feature
